#ifndef DISPLAY_KEY_MAPPING
#define DISPLAY_KEY_MAPPING´

#define DISPLAY_KEY_NONE 0
#define DISPLAY_KEY_SELECT 1
#define DISPLAY_KEY_LEFT 2
#define DISPLAY_KEY_DOWN 3
#define DISPLAY_KEY_UP 4
#define DISPLAY_KEY_RIGHT 5

#endif
